### ISSUE TITLE
起動しない

### ISSUE THREAD

**Issue by yanorei32** [gnknzm/zerono.cloud#3]
なんか上がってこなくなった。ごめん。

状況としては 

- GPUドライバを充てた #1 
- Kernelを更新し古いものを消した 
- docker compose V2にした #2 

です。

**Comment by yanorei32** [comment]
関連しそうな Issue は #1, #2 です。

**Comment by yanorei32** [comment]
## When
2022-08-19 01:00 AM頃

## Where
それぞれの自宅より

## Who
@yanorei32 と @sjcl が

## What
PCを

## Why
Dockerコンテナが起動してこず、

- dockerd
- systemd
- jounralctl

らが、まともに応答しなくなったので

## How
再起動した。

**Comment by yanorei32** [comment]
もし起きたら画面の写真をここにポイしていただけると 助かります @ZEROssk

**Comment by ZEROssk** [comment]
<img src=https://cdn.discordapp.com/attachments/656343134325964804/1009939939972104289/IMG_9440.jpg>

**Comment by ZEROssk** [comment]
ミスった

**Comment by ZEROssk** [comment]
`echo 1 > /sys/module/md_mod/parameters/start_dirty_degraded`
`mdadm --run /dev/md0`
`mdadm --readwrite /dev/md0`
`cat /proc/mdstat`

**Comment by yanorei32** [comment]
![image](https://user-images.githubusercontent.com/11992915/185770971-f47d8218-961d-4a2c-9e87-1ffc0e937e0d.png)
Emergency Modeから抜け忘れてませんか？

**Comment by yanorei32** [comment]
![image](https://user-images.githubusercontent.com/11992915/185771735-d162a723-ff63-4684-9473-980bbcc27d02.png)
ありがとう！！！:bow:

**Comment by sjcl** [comment]
🙏
